name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.4

      - name: Install
        run: |
          haxelib install all --always --quiet
          haxelib list

      - name: Setup Pages
        id: pages_config
        uses: actions/configure-pages@v5

      - name: Generate website
        run: |
          haxe generate.hxml
        env:
          GHP_ROOT: nekovm.org
          # GHP_ROOT: ${{steps.pages_config.outputs.base_url}}

      - name: Publish on GitHub Pages
        if: github.ref == 'refs/heads/master'
        uses: ftnext/action-push-ghpages@v1.0.0
        with:
          build_dir: ./out
          github_token: ${{ secrets.GITHUB_TOKEN }}

