name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.4

      # we are using this version in order to build vscode-textmate
      - name: Setup AWS CLI
        run: |
          pip install --user awscli
          aws --version

      - name: Install
        run: |
          haxelib install all --always --quiet
          haxelib list

      - name: Setup Pages
        id: pages_config
        uses: actions/configure-pages@v5

      - name: Generate website
        run: |
          haxe generate.hxml
        env:
          GHP_ROOT: ${{steps.pages_config.outputs.base_url}}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    if: github.ref == 'refs/heads/master'
    permissions:
      contents: read
      pages: write
      id-token: write

    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - name: Deploy artifact
        id: deployment
        uses: actions/deploy-pages@v4
